/* Copyright (c) 2012 Silk Project.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Silk nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL SILK BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import Silk.HTTP 1.1
import Silk.HTML 5.0
import "../"
import "../components/"

SilkPageTemplate {
    id: http

    subtitle: "Hello QML"

    Article {
        Section {
            H2 { text: "a QML is a plain text file" }
            PlainFile {
                __class: 'qml'
                text: '/* hello.qml */
import Silk.HTTP 1.1
import Silk.HTML 5.0

Http {
    status: 200
    responseHeader: {"Content-Type": "text/html; charset=utf-8;"}

    DocType {}

    Html {
        Head {
            Title { id: title; text: "Hello silk world" }
            Link { rel: "stylesheet"; href: "./hellocss.qml" }
        }
        Body {
            Article {
                Header {
                    H1 { text: title.text }
                }
                Section {
                    P { text: "QML is a Simple and Powerful language" }
                }
                Footer {
                    P { text: "This HTML is generated by silk" }
                }
            }
        }
    }
}'
            }

            PlainFile {
                __class: 'qml'
                text: '/*
Comment
*/
import "components"

Div {
    name: value
    name2: value2
    name3: "value3"
    name4: 1.2

    A { href: "http://abc.def" }
}'
            }


            PlainFile {
                __class: 'qml'
                text: 'import "components"

Div {
    name: value
    name2: value2
    name3: "value3"
    name4: 1.2

    A { href: "http://abc.def" }
}'
            }

            PlainFile {
                __class: 'qml'
                text: 'import "components"

Div {
    name: value
}'
            }

            PlainFile {
                __class: 'qml'
                text: 'import "components"

Div {
}'
            }

            PlainFile {
                __class: 'qml'
                text: '
import Silk 1.0
import Silk.HTTP 1.0
import Silk 1.0 as HTTP
import Silk.HTTP 1.0 as HTTP
import "components"
import "components" as HTTP
import "components" 1.0
import "components" 1.0 as HTTP

Div {
}'
            }

            PlainFile {
                __class: 'qml'
                text: '
import Silk 1.0

Div {
}'
            }

            PlainFile {
                __class: 'qml'
                text: '
import Silk.HTTP 1.0

Div {
}'
            }

            PlainFile {
//                __class: 'json'
                text: '{
    "listen": { "address": "*", "port": 8080 }
    , "contents": { "*": "../contents/root/" }
    , "storage": { "path": "../" }
    , "import": { "path": [] }
    , "cache": { "qml": true }
}'
            }

        }

        Footer {
            Nav {
                A { href: "/config.qml"; text: "Configuration" }
                Text { text: " &lt;&lt; Previous / Next &gt;&gt; " }
                A { href: "/examples/"; text: "Examples" }
            }
        }
    }
}
