/* hello.qml */
import Silk.HTML 5.0

Html {
    Head {
        Title { id: title; text: "Hello silk world" }
        Link { rel: "stylesheet"; href: "./hellocss.qml" }
    }
    Body {
        Article {
            Header {
                H1 { text: title.text }
            }
            Section {
                P { text: "QML is a Simple and Powerful language" }
            }
            Footer {
                P { text: "This HTML is generated by silk" }
            }
        }
    }
}
