/* hello.qml */
import Silk.HTTP 1.1
import Silk.HTML 5.0

Http {
    status: 200
    responseHeader: {"Content-Type": "text/html; charset=utf-8;"}

    DocType {}

    Html {
        Head {
            Title { id: title; text: "Hello silk world" }
            Link { rel: "stylesheet"; href: "./hellocss.qml" }
        }
        Body {
            Article {
                Header {
                    H1 { text: title.text }
                }
                Section {
                    P { text: "QML is a Simple and Powerful language" }
                }
                Footer {
                    P { text: "This HTML is generated by silk" }
                }
            }
        }
    }
}
